import "../styles/globals.css";
import { inter, roboto } from "../app/fonts"; // Импортируем шрифты из fonts.ts

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} ${roboto.variable}`}>
      <body className="font-sans">{children}</body>
    </html>
  );
}
